import assert from 'assert'
import _ from 'lodash-es'
import w from 'wsemi'
import WOrm from '../src/WOrmLmdb.mjs'


describe('autoGenPk', function() {
    let rt = null
    let vans = {}
    let vget = {}

    before(async function() {

        w.fsDeleteFolder('./_db_autogenpk')

        let url = './_db_autogenpk'

        //預設值須為true, 未帶id者自動補值
        let woDef = WOrm({ url, db: 'worm', cl: 'def' })
        await woDef.insert({ name: 'peter' })
        let rsDef = await woDef.select()
        vget[1] = _.size(rsDef)
        vget[2] = w.isestr(_.get(rsDef, '0.id'))
        await woDef.close()

        //明確給true, 行為須與預設相同
        let woTrue = WOrm({ url, db: 'worm', cl: 'ptrue', autoGenPk: true })
        rt = null
        // vans[3] = { n: 2, nInserted: 2, ok: 1 }
        await woTrue.insert([{ name: 'a' }, { name: 'b' }])
            .then(function(msg) {
                rt = msg
            })
            .catch(function(msg) {
                rt = 'reject: ' + msg.toString()
            })
        vget[3] = rt
        vget[4] = _.size(_.filter(await woTrue.select(), function(v) {
            return w.isestr(v.id)
        }))
        await woTrue.close()

        //給false且自備id, 須正常寫入且沿用呼叫端所給之id
        let woFalse = WOrm({ url, db: 'worm', cl: 'pfalse', autoGenPk: false })
        rt = null
        // vans[5] = { n: 2, nInserted: 2, ok: 1 }
        await woFalse.insert([{ id: 'own-1', name: 'a' }, { id: 'own-2', name: 'b' }])
            .then(function(msg) {
                rt = msg
            })
            .catch(function(msg) {
                rt = 'reject: ' + msg.toString()
            })
        vget[5] = rt
        vget[6] = _.map(_.sortBy(await woFalse.select(), 'id'), 'id')

        //給false且save自備id, 須正常處理
        rt = null
        // vans[7] = [{ n: 1, nInserted: 0, nModified: 1, ok: 1 }]
        await woFalse.save({ id: 'own-1', name: 'a2' })
            .then(function(msg) {
                rt = msg
            })
            .catch(function(msg) {
                rt = 'reject: ' + msg.toString()
            })
        vget[7] = rt

        //給false而insert未帶有效id, 須reject且不得有任何寫入
        rt = null
        await woFalse.insert({ name: 'no-id' })
            .then(function(msg) {
                rt = 'resolve: ' + JSON.stringify(msg)
            })
            .catch(function(msg) {
                rt = 'reject'
            })
        vget[8] = rt

        //給false而save未帶有效id, 須reject
        rt = null
        await woFalse.save({ name: 'no-id' })
            .then(function(msg) {
                rt = 'resolve: ' + JSON.stringify(msg)
            })
            .catch(function(msg) {
                rt = 'reject'
            })
        vget[9] = rt

        //給false而整批內僅部份未帶有效id, 須整批reject且不得有部份筆數已寫入
        rt = null
        await woFalse.insert([{ id: 'own-3', name: 'c' }, { name: 'no-id' }])
            .then(function(msg) {
                rt = 'resolve: ' + JSON.stringify(msg)
            })
            .catch(function(msg) {
                rt = 'reject'
            })
        vget[10] = rt
        vget[11] = _.map(_.sortBy(await woFalse.select(), 'id'), 'id')
        await woFalse.close()

        //del不受autoGenPk影響, 未帶有效id者為該筆問題而非整批性錯誤
        let woDel = WOrm({ url, db: 'worm', cl: 'pdel', autoGenPk: false })
        await woDel.insert({ id: 'd1', name: 'x' })
        rt = null
        await woDel.del([{ id: 'd1' }, { name: 'no-id' }])
            .then(function(msg) {
                rt = _.map(msg, function(v) {
                    return _.omit(v, 'err')
                })
            })
            .catch(function(msg) {
                rt = 'reject: ' + msg.toString()
            })
        vget[12] = rt
        await woDel.close()

    })

    vans[1] = 1
    it(`should get ${JSON.stringify(vans[1])} for records by insert without id in default`, async function() {
        assert.strict.deepStrictEqual(vget[1], vans[1])
    })

    vans[2] = true
    it(`should get ${JSON.stringify(vans[2])} for id generated by default`, async function() {
        assert.strict.deepStrictEqual(vget[2], vans[2])
    })

    vans[3] = { n: 2, nInserted: 2, ok: 1 }
    it(`should get ${JSON.stringify(vans[3])} for insert without id by autoGenPk=true`, async function() {
        assert.strict.deepStrictEqual(vget[3], vans[3])
    })

    vans[4] = 2
    it(`should get ${JSON.stringify(vans[4])} for records with generated id by autoGenPk=true`, async function() {
        assert.strict.deepStrictEqual(vget[4], vans[4])
    })

    vans[5] = { n: 2, nInserted: 2, ok: 1 }
    it(`should get ${JSON.stringify(vans[5])} for insert with own id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[5], vans[5])
    })

    vans[6] = ['own-1', 'own-2']
    it(`should get ${JSON.stringify(vans[6])} for keeping own id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[6], vans[6])
    })

    vans[7] = [{ n: 1, nInserted: 0, nModified: 1, ok: 1 }]
    it(`should get ${JSON.stringify(vans[7])} for save with own id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[7], vans[7])
    })

    //autoGenPk為false而未帶有效主鍵屬呼叫端未履行契約, 須為整批性錯誤而非該筆ok為0
    vans[8] = 'reject'
    it(`should get ${JSON.stringify(vans[8])} for insert without id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[8], vans[8])
    })

    vans[9] = 'reject'
    it(`should get ${JSON.stringify(vans[9])} for save without id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[9], vans[9])
    })

    vans[10] = 'reject'
    it(`should get ${JSON.stringify(vans[10])} for insert by array partially without id by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[10], vans[10])
    })

    //檢查須於任何寫入之前完成, 故整批reject時同批之有效筆數亦不得被寫入
    vans[11] = ['own-1', 'own-2']
    it(`should get ${JSON.stringify(vans[11])} for no partial writing when batch rejected`, async function() {
        assert.strict.deepStrictEqual(vget[11], vans[11])
    })

    //del不受autoGenPk影響
    vans[12] = [
        { n: 1, nDeleted: 1, ok: 1 },
        { n: 0, nDeleted: 0, ok: 0 },
    ]
    it(`should get ${JSON.stringify(vans[12])} for del not affected by autoGenPk=false`, async function() {
        assert.strict.deepStrictEqual(vget[12], vans[12])
    })

})
